apiVersion: v1
kind: Service
metadata:
  name: sample-nginx
  namespace: default
  labels:
    app: sample-nginx
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: sample-nginx
