apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    app: test-service
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: test
